# dbt Project for Snowflake
# =========================
# Este directorio contendrá la configuración del proyecto dbt

name: 'retail_forecasting'
version: '1.0.0'

profile: 'retail_forecasting'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
